apiVersion: v1
data:
  .dockercfg: eyJodHRwczovL2Njci5jY3MudGVuY2VudHl1bi5jb20iOnsidXNlcm5hbWUiOiIxMDAwMTI0NzIyNjUiLCJwYXNzd29yZCI6IlRyaWFsQDItMTkiLCJlbWFpbCI6ImJvdEBrb2Rlcm92ZXIuY29tIn19
kind: Secret
metadata:
  name: default-candidate-registry-secret
type: kubernetes.io/dockercfg